apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name}}
  namespace: {{ .Values.name}}
  labels:
    run: {{ .Values.service.name}}
spec:
  ports:
  - port: {{ .Values.ports.port}}
    protocol: TCP
  selector:
    run: {{ .Values.service.name}}